IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'$(APP_NAME)')
BEGIN
    CREATE USER [$(APP_NAME)] FROM EXTERNAL PROVIDER WITH OBJECT_ID = '$(APP_OBJECT_ID)';
END;
GO

ALTER ROLE db_datareader ADD MEMBER [$(APP_NAME)];
ALTER ROLE db_datawriter ADD MEMBER [$(APP_NAME)];
GO
